// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAwXWq32c4JqPbrLSfKTIGtxNF7RKonM',
    appId: '1:440199101878:web:4ba780119a4c8e1e669517',
    messagingSenderId: '440199101878',
    projectId: 'makarr-bc736',
    authDomain: 'makarr-bc736.firebaseapp.com',
    storageBucket: 'makarr-bc736.firebasestorage.app',
    measurementId: 'G-TTKC3T5RL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RlRv25KkomG2NG43ipknML1zzdJtUl8',
    appId: '1:440199101878:android:c077cc1f12990b34669517',
    messagingSenderId: '440199101878',
    projectId: 'makarr-bc736',
    storageBucket: 'makarr-bc736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB82mxKzXE1H8o_bPOwVYdAqLDmb77ZvI',
    appId: '1:440199101878:ios:759bcaa80185381c669517',
    messagingSenderId: '440199101878',
    projectId: 'makarr-bc736',
    storageBucket: 'makarr-bc736.firebasestorage.app',
    iosBundleId: 'com.example.makarr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB82mxKzXE1H8o_bPOwVYdAqLDmb77ZvI',
    appId: '1:440199101878:ios:759bcaa80185381c669517',
    messagingSenderId: '440199101878',
    projectId: 'makarr-bc736',
    storageBucket: 'makarr-bc736.firebasestorage.app',
    iosBundleId: 'com.example.makarr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfAwXWq32c4JqPbrLSfKTIGtxNF7RKonM',
    appId: '1:440199101878:web:97a89001a4ac65b2669517',
    messagingSenderId: '440199101878',
    projectId: 'makarr-bc736',
    authDomain: 'makarr-bc736.firebaseapp.com',
    storageBucket: 'makarr-bc736.firebasestorage.app',
    measurementId: 'G-6W51R2Q2VV',
  );

}